name = "22"
url = "https://222"
description = "22222"
contact_info = "_No response_"
labels = [ "_No response_",]
website = "https://_no response_"
group = "Other"
reference_paper = "https://_no response_"
documentation = "https://_no response_"
uuid = "63cb45e5-ca90-4fcd-90f7-03526f516454"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F63cb45e5)](https://qisk.it/e)"
