name = "kk"
url = "https://kkk"
description = "kkkk"
contact_info = "_No response_"
labels = [ "_No response_",]
website = "https://_no response_"
group = "Other"
reference_paper = "https://_no response_"
documentation = "https://_no response_"
uuid = "969230fc-cc1f-42e3-a4a7-0ea50b9a8a94"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F969230fc)](https://qisk.it/e)"
