name = "k"
url = "https://kkkk"
description = "kkkk"
contact_info = "_No response_"
labels = [ "_No response_",]
website = "https://_no response_"
group = "Other"
reference_paper = "https://_no response_"
documentation = "https://_no response_"
uuid = "4a465f97-565e-4648-a892-953f5fc719ba"
badge = "[![Qiskit Ecosystem](https://img.shields.io/endpoint?style=flat&url=https%3A%2F%2Fqiskit.github.io%2Fecosystem%2Fb%2F4a465f97)](https://qisk.it/e)"
