name = "Qiskit Installer for Windows"
url = "https://github.com/ket-q/qiskit_windows_installer"
description = "Set up Qiskit and Visual Studio Code (VS Code), with a ready-to-use virtual environment for Jupyter notebooks or Python files."
licence = "GNU General Public License (GPL)"
contact_info = "axelpetit@yonsei.ac.kr"
affiliations = ""
labels = []
website = "https://ket-q.github.io/qiskit_windows_installer/"
group = "Other"
uuid = "7352f04f-0223-4082-bdd9-9e3e207a35da"
badge = "https://qisk.it/e-7352f04f"

[github]
url = "https://github.com/ket-q/qiskit_windows_installer"
owner = "ket-q"
repo = "qiskit_windows_installer"
stars = 0
license = "Other"
description = "Installer for Qiskit on Microsoft Windows platforms."
estimated_contributors = 2
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-08-19T14:42:30Z

[validation.L09]
id = "L09"
status = "WARNING"
details = "members should have, at least, one label. See the list of possible labels in https://github.com/Qiskit/ecosystem/blob/main/ecosystem/resources/labels.toml"
affects = "labels"
last_check = 2026-01-03T12:58:55
failing_since = 2025-12-21T18:20:59
