name = "QPong"
url = "https://github.com/QPong/QPong"
description = "A quantum version of the classic game Pong built with Qiskit and PyGame."
licence = "Apache 2.0"
contact_info = "ukskosana@gmail.com"
labels = []
created_at = 1678827877.979398
updated_at = 1678827877.979398
group = "Game"
uuid = "56eb0ca6-4dd5-4954-a059-96256fd0ab26"
badge = "https://qisk.it/e-56eb0ca6"

[github]
url = "https://github.com/QPong/QPong"
owner = "QPong"
repo = "QPong"
stars = 122
license = "Apache License 2.0"
description = "A quantum version of the classic Pong"
estimated_contributors = 9
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2024-06-15T20:19:28Z
last_activity = 2025-12-08T19:31:02Z

[validation.L09]
id = "L09"
status = "WARNING"
details = "members should have, at least, one label. See the list of possible labels in https://github.com/Qiskit/ecosystem/blob/main/ecosystem/resources/labels.toml"
affects = "labels"
last_check = 2026-01-03T13:02:18
failing_since = 2025-12-21T18:21:06
