name = "test_5"
url = "https://github.com/1ucian0/ecosystem"
description = "test_5"
labels = []
group = "High-level synthesis plugin"
packages = []
uuid = "21f68e42-a884-4bd4-96c7-7962d4c89776"

[github]
url = "https://github.com/1ucian0/ecosystem"
owner = "1ucian0"
repo = "ecosystem"
stars = 0
license = "Apache License 2.0"
total_dependent_repositories = 0
total_dependent_packages = 0
last_commit = 2025-12-10T23:25:08Z
last_activity = 2025-12-10T23:25:48Z
