name: Create stats and badges

on:
  pull_request_review:
    types: [submitted]

jobs:
  create_stats:
    if: >
      github.event.review.state == 'approved'
      && startsWith(github.event.pull_request.title, 'Add ')
      && contains(github.event.pull_request.labels.*.name, 'submission')
    runs-on: ubuntu-latest
    steps:
      - name: Update stats
        run: echo "${{ github.event.pull_request }}"